version: '3'
services:
  app:
    build: .
    container_name: cleancar
    volumes:
      - .:/app
    command: >
      sh -c "chown -R 998:998 build/ && chown -R 998:998 node_modules/ && yarn install && yarn build"