# curl -X 'GET'
#  'https://dev.server.clean-car.net/api/companies/list_company_performer/'
#  -H 'accept: application/json'
#  -H 'Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzAxMzI5Njc3LCJpYXQiOjE3MDEzMjkzNzcsImp0aSI6IjAxNjNiOTEwMmYyZTQzZTY5ZGYwZWU3YWU4YmIxMDgxIiwidXNlcl9pZCI6NCwiZmlyc3RfbmFtZSI6IiIsImxhc3RfbmFtZSI6IiIsInBob25lIjpudWxsfQ.T4QsAZaDSuzx4JFs6jmaBkepjX-dd15PfaMk3LolQdU'
#  -H 'X-CSRFToken: 5C1pDxC8FJofj0eytBnPjFPjSf5M6FlnwlyKPw1hyqYnSafr0nwYL7hDPZRQWvoG'
GET https://dev.server.clean-car.net/api/companies/list_company_performer/
accept: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzAxMzMwMTI4LCJpYXQiOjE3MDEzMjk4MjgsImp0aSI6Ijk3N2VmODE0NjA4YzQ2NGQ4NWQ4YTJjMzViNTk2YTU3IiwidXNlcl9pZCI6NCwiZmlyc3RfbmFtZSI6IiIsImxhc3RfbmFtZSI6IiIsInBob25lIjpudWxsfQ.Wra8BL8O9Ei1fWYKRw0OMO23GMb6AEtue_JgprF53DU

###

# curl -X 'POST'
#  'https://dev.server.clean-car.net/api/token/'
#  -H 'accept: application/json'
#  -H 'Content-Type: application/json'
#  -H 'X-CSRFToken: 5C1pDxC8FJofj0eytBnPjFPjSf5M6FlnwlyKPw1hyqYnSafr0nwYL7hDPZRQWvoG'
#  -d '{
#  "email": "prweb2012@gmail.com",
#  "password": "lKC7S8iP"
#}'
POST https://dev.server.clean-car.net/api/token/
accept: application/json
X-CSRFToken: 5C1pDxC8FJofj0eytBnPjFPjSf5M6FlnwlyKPw1hyqYnSafr0nwYL7hDPZRQWvoG
Content-Type: application/json

{
  "email": "prweb2012@gmail.com",
  "password": "lKC7S8iP"
}

###

POST http://localhost:80/api/item
Content-Type: application/json

{}

###
