# curl -X 'POST'
#  'https://dev.server.clean-car.net/api/accounts_admin/upload_users/'
#  -H 'accept: application/json'
#  -H 'authorization: Basic YWRtaW5AYWRtaW4uY29tOnZYSzJYREFH'
#  -d ''
POST https://dev.server.clean-car.net/api/accounts_admin/upload_users/
accept: application/json
authorization: Basic YWRtaW5AYWRtaW4uY29tOnZYSzJYREFH
Content-Type: application/x-www-form-urlencoded

###

# curl -X 'POST'
#  'https://dev.server.clean-car.net/api/accounts_admin/upload_users/'
#  -H 'accept: application/json'
#  -H 'authorization: Basic YWRtaW5AYWRtaW4uY29tOnZYSzJYREFH'
#  -d ''
POST https://dev.server.clean-car.net/api/accounts_admin/upload_users/
accept: application/json
authorization: Basic YWRtaW5AYWRtaW4uY29tOnZYSzJYREFH
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="users_xlsx"
Content-Type: text/plain

Name
--WebAppBoundary
Content-Disposition: form-data; name="users_xlsx"; filename="name.xlsx";
Content-Type: application/json

< name.xlsx
--WebAppBoundary--
###

# curl -X 'POST'
#  'https://dev.server.clean-car.net/api/accounts_admin/upload_users/'
#  -H 'accept: application/json'
#  -H 'authorization: Basic YWRtaW5AYWRtaW4uY29tOnZYSzJYREFH'
#  -d ''
POST https://dev.server.clean-car.net/api/accounts_admin/upload_users/
accept: application/json
authorization: Basic YWRtaW5AYWRtaW4uY29tOnZYSzJYREFH
Content-Disposition: form-data; name="data"; filename="name.xlsx"

